server:
  port: 8220
  undertow:
    max-http-post-size: 0
    io-threads: 8
    worker-threads: 64
    buffer-size: 1024
    direct-buffers: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hecc_job?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 5
      connection-timeout: 5000
      idle-timeout: 180000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    org:
      springframework: INFO
    com:
      sioo: INFO
  file.max-size: 10MB

